"""Turn course text into a study sheet, with Claude, Gemini, a recording, or a placeholder."""

import hashlib
import json
import logging
import os
from pathlib import Path
from typing import Protocol

import anthropic
import httpx
import pydantic
from google import genai
from google.genai import errors as genai_errors
from google.genai import types as genai_types

from app.extraction import Course
from app.prompts import fill_prompt
from app.schemas import Section, StudySheet

logger = logging.getLogger(__name__)


class GenerationError(Exception):
    """The study sheet could not be generated; the message says why."""


class SheetGenerator(Protocol):
    name: str
    prompt_version: str | None

    def generate(self, course: Course) -> StudySheet: ...


class ClaudeSheetGenerator:
    def __init__(
        self,
        model: str,
        prompt_template: str,
        prompt_version: str,
        client: anthropic.Anthropic | None = None,
    ):
        self.name = model
        self.prompt_version = prompt_version
        self._template = prompt_template
        self._client = client or anthropic.Anthropic()

    def generate(self, course: Course) -> StudySheet:
        prompt = fill_prompt(self._template, course.to_prompt_text())
        try:
            response = self._client.beta.messages.parse(
                model=self.name,
                max_tokens=16000,
                messages=[{"role": "user", "content": prompt}],
                # The SDK turns the Pydantic model into the output schema and
                # validates the answer against it.
                output_format=StudySheet,
                output_config={"effort": "medium"},
                # If the model declines for safety reasons, the API retries on
                # Anthropic's recommended fallback model.
                betas=["server-side-fallback-2026-07-01"],
                fallbacks="default",
            )
        except pydantic.ValidationError as error:
            raise GenerationError(
                "The AI answer was not a valid study sheet (it may have been cut "
                "off). Try again."
            ) from error
        except anthropic.AuthenticationError as error:
            raise GenerationError(
                "The Anthropic API key was rejected. Check ANTHROPIC_API_KEY in "
                "backend/.env."
            ) from error
        except anthropic.RateLimitError as error:
            raise GenerationError(
                "Too many requests to the Anthropic API. Wait a minute and try again."
            ) from error
        except anthropic.APIStatusError as error:
            raise GenerationError(
                f"The Anthropic API returned an error ({error.status_code}): "
                f"{error.message}"
            ) from error
        except anthropic.APIConnectionError as error:
            raise GenerationError(
                "Could not reach the Anthropic API. Check the internet connection."
            ) from error

        logger.info(
            "Study sheet generated by %s: %s input tokens, %s output tokens",
            response.model,
            response.usage.input_tokens,
            response.usage.output_tokens,
        )
        if response.stop_reason == "refusal":
            raise GenerationError("The AI declined to summarize this course.")
        if response.parsed_output is None:
            raise GenerationError(
                f"The AI returned no study sheet (stop reason: {response.stop_reason})."
            )
        return response.parsed_output


# Answers that mean "try again later": the free tier's main model is often busy
# (503) or out of its per-minute quota (429). The next model has its own quota.
RETRYABLE_GEMINI_CODES = {429, 500, 503, 504}


class GeminiSheetGenerator:
    """Study sheet from Google's Gemini API, free tier of Google AI Studio.

    Same prompt and same output schema as the Claude generator. Models are tried
    in order: when one is busy or out of quota, the next one answers instead, and
    the sheet records which model actually wrote it.
    """

    def __init__(
        self,
        models: list[str],
        prompt_template: str,
        prompt_version: str,
        client: genai.Client | None = None,
    ):
        self._models = list(dict.fromkeys(model for model in models if model))
        self.name = self._models[0]
        self.prompt_version = prompt_version
        self._template = prompt_template
        # Kept on the instance: a client dropped mid-request closes its connection.
        self._client = client or genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

    def generate(self, course: Course) -> StudySheet:
        prompt = fill_prompt(self._template, course.to_prompt_text())
        # The SDK turns the Pydantic model into the output schema, as for Claude.
        config = genai_types.GenerateContentConfig(
            response_mime_type="application/json", response_schema=StudySheet
        )
        for model in self._models:
            try:
                response = self._client.models.generate_content(
                    model=model, contents=prompt, config=config
                )
            except genai_errors.APIError as error:
                if error.code in RETRYABLE_GEMINI_CODES and model != self._models[-1]:
                    logger.warning(
                        "Gemini model %s unavailable (%s), trying the next one",
                        model,
                        error.code,
                    )
                    continue
                raise GenerationError(_describe_gemini_error(error)) from error
            except httpx.TransportError as error:
                raise GenerationError(
                    "Could not reach the Gemini API. Check the internet connection."
                ) from error
            self.name = model
            return _read_gemini_sheet(response, model)
        raise GenerationError("No Gemini model is configured.")


def _read_gemini_sheet(response, model: str) -> StudySheet:
    usage = response.usage_metadata
    if usage is not None:
        logger.info(
            "Study sheet generated by %s: %s input tokens, %s output tokens",
            model,
            usage.prompt_token_count,
            usage.candidates_token_count,
        )
    feedback = response.prompt_feedback
    if feedback is not None and feedback.block_reason:
        raise GenerationError("The AI declined to summarize this course.")
    candidate = (response.candidates or [None])[0]
    finish = str(getattr(candidate, "finish_reason", "") or "")
    if "SAFETY" in finish:
        raise GenerationError("The AI declined to summarize this course.")
    if isinstance(response.parsed, StudySheet):
        return response.parsed
    try:
        return StudySheet.model_validate_json(response.text or "")
    except pydantic.ValidationError as error:
        raise GenerationError(
            "The AI answer was not a valid study sheet (it may have been cut "
            "off). Try again."
        ) from error


def _describe_gemini_error(error: genai_errors.APIError) -> str:
    message = error.message or ""
    if error.code in (401, 403) or "API key" in message:
        return "The Gemini API key was rejected. Check GEMINI_API_KEY in backend/.env."
    if error.code == 429:
        return (
            "The free Gemini quota is used up for now. Wait a minute and try "
            "again; the daily quota resets the next day."
        )
    if error.code == 503:
        return "Gemini is overloaded right now. Wait a minute and try again."
    return f"The Gemini API returned an error ({error.code}): {message}"


class FakeSheetGenerator:
    """Placeholder sheet made from the course itself, without any AI call.

    It lets the team work on the interface without an API key or cost. Each
    section is the first line of a page or slide followed by the next lines.
    """

    name = "fake"
    prompt_version = None

    def generate(self, course: Course) -> StudySheet:
        units = [unit for unit in course.units if unit.text]
        sections = []
        for unit in units[:8]:
            title, *rest = unit.text.splitlines()
            sections.append(
                Section(title=title, points=rest[:3] or [title], sources=[unit.number])
            )
        return StudySheet(title=units[0].text.splitlines()[0], sections=sections)


def course_signature(course: Course) -> str:
    """Identify a course by the exact text that would be sent to the model."""
    digest = hashlib.sha256(course.to_prompt_text().encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


class FixtureSheetGenerator:
    """Serve a sheet recorded earlier, and a placeholder for any other course.

    It exists so the application can be shown with real content while no API key
    is available. A recording only describes the course it was made from, so
    uploading a different course falls back to the placeholder generator rather
    than answering with a sheet about something else.

    Which path was taken is visible afterwards: the generator reports itself as
    "fixture" when it served the recording and as "fake" when it fell back, and
    that name is stored with the sheet. A new instance is built for each request,
    so setting it during generation is safe.
    """

    def __init__(self, path: Path, fallback: "SheetGenerator | None" = None):
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
            self._recorded_version = record["recorded"]["prompt_version"]
            self._signature = record["course_signature"]
            self._sheet = StudySheet.model_validate(record["sheet"])
        except (OSError, ValueError, KeyError) as error:
            raise GenerationError(
                f"The recorded sheet {path} could not be read: {error}"
            ) from error
        self._fallback = fallback or FakeSheetGenerator()
        self.name = "fixture"
        self.prompt_version = self._recorded_version

    def generate(self, course: Course) -> StudySheet:
        if course_signature(course) == self._signature:
            self.name = "fixture"
            self.prompt_version = self._recorded_version
            return self._sheet.model_copy(deep=True)

        logger.info(
            "Course does not match the recorded one: falling back to %s",
            self._fallback.name,
        )
        self.name = self._fallback.name
        self.prompt_version = self._fallback.prompt_version
        return self._fallback.generate(course)
