"""Turn course text into a study sheet, with Claude, a recording, or a placeholder."""

import hashlib
import json
import logging
from pathlib import Path
from typing import Protocol

import anthropic
import pydantic

from app.extraction import Course
from app.prompts import fill_prompt
from app.schemas import Section, StudySheet

logger = logging.getLogger(__name__)


class GenerationError(Exception):
    """The study sheet could not be generated; the message says why."""


class SheetGenerator(Protocol):
    name: str
    prompt_version: str | None

    def generate(self, course: Course) -> StudySheet: ...


class ClaudeSheetGenerator:
    def __init__(
        self,
        model: str,
        prompt_template: str,
        prompt_version: str,
        client: anthropic.Anthropic | None = None,
    ):
        self.name = model
        self.prompt_version = prompt_version
        self._template = prompt_template
        self._client = client or anthropic.Anthropic()

    def generate(self, course: Course) -> StudySheet:
        prompt = fill_prompt(self._template, course.to_prompt_text())
        try:
            response = self._client.beta.messages.parse(
                model=self.name,
                max_tokens=16000,
                messages=[{"role": "user", "content": prompt}],
                # The SDK turns the Pydantic model into the output schema and
                # validates the answer against it.
                output_format=StudySheet,
                output_config={"effort": "medium"},
                # If the model declines for safety reasons, the API retries on
                # Anthropic's recommended fallback model.
                betas=["server-side-fallback-2026-07-01"],
                fallbacks="default",
            )
        except pydantic.ValidationError as error:
            raise GenerationError(
                "The AI answer was not a valid study sheet (it may have been cut "
                "off). Try again."
            ) from error
        except anthropic.AuthenticationError as error:
            raise GenerationError(
                "The Anthropic API key was rejected. Check ANTHROPIC_API_KEY in "
                "backend/.env."
            ) from error
        except anthropic.RateLimitError as error:
            raise GenerationError(
                "Too many requests to the Anthropic API. Wait a minute and try again."
            ) from error
        except anthropic.APIStatusError as error:
            raise GenerationError(
                f"The Anthropic API returned an error ({error.status_code}): "
                f"{error.message}"
            ) from error
        except anthropic.APIConnectionError as error:
            raise GenerationError(
                "Could not reach the Anthropic API. Check the internet connection."
            ) from error

        logger.info(
            "Study sheet generated by %s: %s input tokens, %s output tokens",
            response.model,
            response.usage.input_tokens,
            response.usage.output_tokens,
        )
        if response.stop_reason == "refusal":
            raise GenerationError("The AI declined to summarize this course.")
        if response.parsed_output is None:
            raise GenerationError(
                f"The AI returned no study sheet (stop reason: {response.stop_reason})."
            )
        return response.parsed_output


class FakeSheetGenerator:
    """Placeholder sheet made from the course itself, without any AI call.

    It lets the team work on the interface without an API key or cost. Each
    section is the first line of a page or slide followed by the next lines.
    """

    name = "fake"
    prompt_version = None

    def generate(self, course: Course) -> StudySheet:
        units = [unit for unit in course.units if unit.text]
        sections = []
        for unit in units[:8]:
            title, *rest = unit.text.splitlines()
            sections.append(
                Section(title=title, points=rest[:3] or [title], sources=[unit.number])
            )
        return StudySheet(title=units[0].text.splitlines()[0], sections=sections)


def course_signature(course: Course) -> str:
    """Identify a course by the exact text that would be sent to the model."""
    digest = hashlib.sha256(course.to_prompt_text().encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


class FixtureSheetGenerator:
    """Serve a sheet recorded earlier, for the one course it was recorded from.

    It exists so the application can be shown with real content while no API key
    is available. It is not an AI call and does not stand in for one: a sheet
    recorded from another course would say nothing about the one uploaded, so
    any other course is refused rather than answered with the wrong sheet.

    The recording carries the model and the interface that produced it, which
    the API returns as the generator so nothing presents it as a live call.
    """

    name = "fixture"

    def __init__(self, path: Path):
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
            self.prompt_version = record["recorded"]["prompt_version"]
            self._signature = record["course_signature"]
            self._sheet = StudySheet.model_validate(record["sheet"])
        except (OSError, ValueError, KeyError) as error:
            raise GenerationError(
                f"The recorded sheet {path} could not be read: {error}"
            ) from error
        self._name = path.name

    def generate(self, course: Course) -> StudySheet:
        if course_signature(course) != self._signature:
            raise GenerationError(
                f"The recorded sheet in {self._name} was made from a different "
                "course, so it says nothing about this one. Upload the course it "
                "was recorded from, or set STUDY_SHEET_GENERATOR to claude for a "
                "real summary or to fake for a placeholder."
            )
        return self._sheet.model_copy(deep=True)
