/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sheets
         * @description The subject library: saved sheets, newest first, filtered by tag.
         */
        get: operations["list_sheets_api_sheets_get"];
        put?: never;
        /** Create Sheet */
        post: operations["create_sheet_api_sheets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sheets/{sheet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Sheet */
        get: operations["read_sheet_api_sheets__sheet_id__get"];
        put?: never;
        post?: never;
        /** Delete Sheet */
        delete: operations["delete_sheet_api_sheets__sheet_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sheets/{sheet_id}/sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Edit Sheet
         * @description Save the student's version. The version the AI wrote is kept aside.
         */
        put: operations["edit_sheet_api_sheets__sheet_id__sheet_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sheets/{sheet_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Sheet
         * @description Undo every edit by putting the AI version back.
         */
        post: operations["restore_sheet_api_sheets__sheet_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sheets/{sheet_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Tags */
        put: operations["set_tags_api_sheets__sheet_id__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Tell clients that the API is running, and how it makes sheets.
         *
         *     The interface shows the generator so a student knows whether to expect a
         *     real summary, a recorded one or a placeholder before uploading anything.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_sheet_api_sheets_post */
        Body_create_sheet_api_sheets_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Generator
             * @description How sheets are made: "claude", "fixture" or "fake"
             */
            generator: string;
        };
        /** Section */
        Section: {
            /**
             * Title
             * @description Short heading of the section
             */
            title: string;
            /**
             * Points
             * @description Key ideas of the section, one short sentence or formula each
             */
            points: string[];
            /**
             * Sources
             * @description Numbers of the pages or slides this section is based on
             */
            sources: number[];
        };
        /**
         * SheetSummary
         * @description One card of the subject library.
         */
        SheetSummary: {
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /** Title */
            title: string;
            /** File Name */
            file_name: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "page" | "slide";
            /** Source Count */
            source_count: number;
            /** Word Count */
            word_count: number;
            /** Section Count */
            section_count: number;
            /**
             * Preview
             * @description Headings of the first sections, to show what the sheet covers
             */
            preview: string[];
            /** Tags */
            tags: string[];
            /** Edited */
            edited: boolean;
        };
        /**
         * StoredSheet
         * @description A saved sheet: the generation result plus what persistence adds.
         */
        StoredSheet: {
            /** File Name */
            file_name: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "page" | "slide";
            /**
             * Source Count
             * @description Number of pages or slides in the file
             */
            source_count: number;
            sheet: components["schemas"]["StudySheet"];
            /** Word Count */
            word_count: number;
            /**
             * Warnings
             * @description Problems found by the automatic checks, for the student to review
             */
            warnings: string[];
            /**
             * Generator
             * @description Model that wrote the sheet, or "fake"
             */
            generator: string;
            /** Prompt Version */
            prompt_version: string | null;
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /** Tags */
            tags: string[];
            /**
             * Edited
             * @description True once the student changed the version the AI wrote
             */
            edited: boolean;
        };
        /** StudySheet */
        StudySheet: {
            /**
             * Title
             * @description Title of the course
             */
            title: string;
            /** Sections */
            sections: components["schemas"]["Section"][];
        };
        /** TagsUpdate */
        TagsUpdate: {
            /**
             * Tags
             * @description Subject tags, replacing the current ones
             */
            tags: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sheets_api_sheets_get: {
        parameters: {
            query?: {
                tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sheet_api_sheets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_sheet_api_sheets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredSheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_sheet_api_sheets__sheet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredSheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sheet_api_sheets__sheet_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_sheet_api_sheets__sheet_id__sheet_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudySheet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredSheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_sheet_api_sheets__sheet_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredSheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tags_api_sheets__sheet_id__tags_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sheet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredSheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
