/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sheet */
        post: operations["create_sheet_api_sheets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Tell clients that the API is running.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_sheet_api_sheets_post */
        Body_create_sheet_api_sheets_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Section */
        Section: {
            /**
             * Title
             * @description Short heading of the section
             */
            title: string;
            /**
             * Points
             * @description Key ideas of the section, one short sentence or formula each
             */
            points: string[];
            /**
             * Sources
             * @description Numbers of the pages or slides this section is based on
             */
            sources: number[];
        };
        /** StudySheet */
        StudySheet: {
            /**
             * Title
             * @description Title of the course
             */
            title: string;
            /** Sections */
            sections: components["schemas"]["Section"][];
        };
        /**
         * StudySheetResponse
         * @description Result of uploading a course: the sheet and what we know about it.
         */
        StudySheetResponse: {
            /** File Name */
            file_name: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "page" | "slide";
            /**
             * Source Count
             * @description Number of pages or slides in the file
             */
            source_count: number;
            sheet: components["schemas"]["StudySheet"];
            /** Word Count */
            word_count: number;
            /**
             * Warnings
             * @description Problems found by the automatic checks, for the student to review
             */
            warnings: string[];
            /**
             * Generator
             * @description Model that wrote the sheet, or "fake"
             */
            generator: string;
            /** Prompt Version */
            prompt_version: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_sheet_api_sheets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_sheet_api_sheets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySheetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
